version: '2'
services:

  nginx:
    build: ./nginx
    depends_on:
      - api
    ports:
      - "8080:8080"

  api:
    build: ./api
    ports:
      - "4567"
    depends_on:
      - db

  db:
    build: ./db
    ports:
      - "5432"
