version: '2'
services:
  
  nginx:
    build: ./nginx
    depends_on:
      - server
    ports:
      - "8080:80"

  api:
    build: ./api
    ports:
      - "8080"
    depends_on:
      - db

  db:
    build: ./db
    ports:
      - "5432"
